services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xh_admin_panel
    restart: unless-stopped
    network_mode: host
    environment:
      ADMIN_PORT: ${ADMIN_PORT:-8051}
